# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyProto.proto\x12\x05greet\"\x1d\n\rNumberRequest\x12\x0c\n\x04name\x18\x01 \x01(\x05\"\xb6\x01\n\x0eNumberResponse\x12\x10\n\x08recieved\x18\x01 \x01(\x08\x12\x11\n\tnumberCPU\x18\x02 \x01(\x05\x12\x11\n\tnumberRAM\x18\x03 \x01(\x05\x12\x12\n\nnumberDISK\x18\x04 \x01(\x05\x12\x15\n\rnumberCPUFreq\x18\x05 \x01(\x05\x12\x15\n\rnumberLoadAvg\x18\x06 \x01(\x05\x12\x15\n\rnumberBattery\x18\x07 \x01(\x05\x12\x13\n\x0bnumberCores\x18\x08 \x03(\x01\x32M\n\x0cGreetService\x12=\n\nGetNumbers\x12\x14.greet.NumberRequest\x1a\x15.greet.NumberResponse\"\x00\x30\x01\x42\x0e\xaa\x02\x0bSignalRChatb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\013SignalRChat'
  _NUMBERREQUEST._serialized_start=24
  _NUMBERREQUEST._serialized_end=53
  _NUMBERRESPONSE._serialized_start=56
  _NUMBERRESPONSE._serialized_end=238
  _GREETSERVICE._serialized_start=240
  _GREETSERVICE._serialized_end=317
# @@protoc_insertion_point(module_scope)
